name: "Bandit Security Scan"

on:
  push:
    branches:
      - main # Runs the scan on pushes to the main branch
  pull_request:
    branches:
      - main # Runs the scan on pull requests made to the main branch

jobs:
  bandit:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out the repository code

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit  # Installs Bandit

      - name: Run Bandit security scan
        run: bandit -r app.py  # Scans the app.py file for security issues
